name: Telefonistka
# Controls when the workflow will run "closed" is used for prmoting changes, "opened"/"synchronize" are needed to warn on drift.
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    types: 
      - closed
      - opened
      - synchronize
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  telefonistka:
    runs-on: ubuntu-latest
    container:
      image: odedbenozer/telefonistka:alpine-v0.1.11
      env:
        GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        APPROVER_GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TEMPLATES_PATH: "/telefonistka/templates/"
    steps:
      - name: Telefonistka
        run: /telefonistka/bin/telefonistka event
  triggerWorkflow:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Workflow
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'telefonistka.yml',
            ref: 'main'
          })
